### ISSUE TITLE
Install via pip

### ISSUE THREAD

**Issue by alex-leonhardt** [mitsuhiko/platter#2]
Hi, am trying to install via pip but : 

```
Collecting platter
  Could not find any downloads that satisfy the requirement platter
  No distributions at all found for platter
```

Any pointers ? 

```
pip 6.0.8 from /Library/Python/2.7/site-packages/pip-6.0.8-py2.7.egg (python 2.7)
```

Thanks!
Alex

**Comment by chhantyal** [comment]
I guess it's not uploaded on PyPi yet as it is still in early dev version. You can install using Github though.

`pip install https://github.com/mitsuhiko/platter/archive/master.zip`

**Comment by alex-leonhardt** [comment]
that worked, thanks! :+1:
