### ISSUE TITLE
Platter can't be installed from PyPI

### ISSUE THREAD

**Issue by sfermigier** [mitsuhiko/platter#37]
```
➜  abilian-sbe git:(master) ✗ pip install platter
Collecting platter
  Could not find a version that satisfies the requirement platter (from versions: )
No matching distribution found for platter
```

See also: <https://pypi.python.org/pypi/platter/1.0-dev>

**Comment by vindarel** [comment]
I think it's still not on Pypi, but we can install it with:

    pip install https://github.com/mitsuhiko/platter/archive/master.zip

**Comment by RR2DO2** [comment]
Closed since it is available on PyPi nowadays.
