### ISSUE TITLE
Cannot pip install platter

### ISSUE THREAD

**Issue by warsaw** [mitsuhiko/platter#8]
From http://platter.pocoo.org/dev/quickstart/

Platter can be installed into a virtual environment with pip:

```
$ virtualenv venv
$ ./venv/bin/pip install platter
```

However:

```
% pip install platter
Downloading/unpacking platter
  Could not find any downloads that satisfy the requirement platter
Cleaning up...
No distributions at all found for platter
```

Seems like there's no platter release on PyPI.

**Comment by mitsuhiko** [comment]
It's not on PyPI yet.  Work in progress :)

**Comment by warsaw** [comment]
On Feb 18, 2015, at 03:53 PM, Armin Ronacher wrote:

> It's not on PyPI yet.  Work in progress :)

I look for to it!  You might want to mention that in the online docs in the
meantime. :)
